# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          repository: guilherme-miyake/guilherme-miyake.github.io
          path: ./deploy

      - uses: actions/setup-node@v2
        with:
            node-version: '14.x'
            cache: 'yarn'
            
      - run: yarn install
      - run: yarn build
      
      - run: rm -r ./deploy/*
      - run: cp -r ./public/* ./deploy

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
        with:
          source-directory: 'deploy'
          destination-github-username: 'guilherme-miyake'
          destination-repository-name: 'guilherme-miyake.github.io'
          user-email: gui.fido@gmail.com
